CREATE TABLE Ms_Collection
(
		Code				varchar(255),
		M_Date				varchar(255),
		M_RecepientName		varchar(255),
        M_RecepientPhoneNo	varchar(255),
        M_RecepientDate		varchar(255),
        M_RecepientAccNo	varchar(255),
		M_CashAmount		varchar(255),
		M_Balance			varchar(255),
		M_szProtocol		varchar(255),
		M_TransactionStatus	varchar(255) NOT NULL,
		M_TransactionCost	varchar(255),
        M_Address			varchar(255),
        M_Type				varchar(255),
        M_Subject			varchar(255),
        M_Body				varchar(2000),
        M_Toa				varchar(255),
        M_Sc_toa			varchar(255),
        M_Service_center	varchar(255),
        M_Read				varchar(255),
        M_Locked			varchar(255),
        M_Date_sent			varchar(255),
		M_Status			varchar(255),
        M_Sub_id			varchar(255),
        M_Readable_date		varchar(255),
        M_szContact_name	varchar(255),
        M_Quota				varchar(255),
        M_FulizaLimit		varchar(255),
        M_FulizaBorrowed	varchar(255),
        M_FulizaCharge		varchar(255),
        M_FulizaAmount		varchar(255)
);